# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  cicd-tests-and-lint:
    steps:
      - checkout
      - run:
          name: Install npm packages
          command: npm install
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Run linter
          command: npm run lint

workflows:
  example-workflow:
    jobs:
      - cicd-tests-and-lint
