# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.7
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  cicd-tests-and-lint:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install npm packages
          command: npm install
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: CD - Deploy the service
          command: curl "https://api.render.com/deploy/srv-chr47oorddlba9q7e01g?key=kjJviPySHWA"

workflows:
  example-workflow:
    jobs:
      - cicd-tests-and-lint
